---
title: "Quicken Loans Case Study"
author: "Guanglai Li"
date: "6/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## The problem set
To decide to call which client that has better conversion rate.

What happens: A bank agent calls a client. The client decides whether to subscribe a term deposit. The outcome is "yes" or "no".


Rank by probability, choose a cutoff by considering cost and gain, which is not available now.


Use the best results from this [paper](http://media.salford-systems.com/video/tutorial/2015/targeted_marketing.pdf) as baseline model.

To make useful predictive models, values of features must be known at time of prediction.

Temporal train-test splitting to predict for future

Use easy to collect features for predictive model


### bank client data: 
for existing bank client so the bank client data is known

duration is not known before call so has no predictive value


### Other attributes
- pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)

### social and economic context attributes

